### ISSUE TITLE
Capability generate User-Defined Type Guards (enable basic TypeCheck at Runtime)

### ISSUE THREAD

**Issue by CanKattwinkel** [dzuvic/jtsgen#27]
Since we are working with plain objects in JavaScript and not with class-instances we can't do `typeof` checks. TypeScript has a feature called _Type Guards_ that can help you with that. 

**Example:**
```

class Person {
  name: string;
  age: number;
  mail: string;
  optionalVal?: any;
}

const person: Person = {
  name: 'Can',
  age: 6,
  mail: 'can@mail.mail'
};

const notAPerson =  {
  name: 'Can',
  mail: 'can@mail.mail'
};
console.log(typeof person, typeof person === typeof Person); // --> 'object', false :(



// with a  'typeguard' function 
function instanceOfPerson(object: any): object is Person {
  return 'name' in object
      && 'age' in object
      && 'mail' in object;
}

// usage:
console.log(typeof person, instanceOfPerson(person)); // --> 'object', true :)
console.log(typeof person, instanceOfPerson(notAPerson)); // --> 'object', false :)

```
https://codepen.io/anon/pen/weJbEr

So it'd be nice to have a setting || annotation to enable the generation for instanceOfX functions. 

[User-Defined Type Guards - TypeScript Docs
](https://www.typescriptlang.org/docs/handbook/advanced-types.html)

[TypeScript Deep Dive](https://basarat.gitbooks.io/typescript/content/docs/types/typeGuard.html#user-defined-type-guards)

**Comment by dzuvic** [comment]
Thank you. I hope it will be implemented in the 0.3.x milestone.

**Comment by pburgmer** [comment]
Proposal: implement as static method on Person class. So we can call Person.isInstance(object)

**Comment by dzuvic** [comment]
Note: Classes will be Implemented with #31 . As far as i know, interfaces don't take concrete implementations. Meaning: functions with this tickets and class members in #31

**Comment by dzuvic** [comment]
There are several issues to be resolved:
* The JSON mapper might exclude some fields, so the type guard should be somehow configurable. this is out of scope for  0.3.0
* it's hard to detect a optional type in jtsgen and  is not supported. Even if you define a mapping like `abc -> abc?` This is out of scope for 0.3.0, also
* The fileds of the super types have to be included.

**Comment by dzuvic** [comment]
First try using undefined: 

```
  export interface InterFaceTestTypeGuard1 {
    typeGuard1: string;
  }


  export function instanceOfInterFaceTestTypeGuard1(x: any): x is InterFaceTestTypeGuard1{
    return x &&
      x.typeGuard1 !== undefined;
  }
```

@CanKattwinkel is this the right way?

**Comment by dzuvic** [comment]
added handling of supertypes: IMHO this feature is ready to be tested.
