### ISSUE TITLE
Kotlin Boolean doesn't show up

### ISSUE THREAD

**Issue by sengmann** [dzuvic/jtsgen#42]
When using Kotlin and jtsgen classes with boolean members will not convert properly. Minimal example: 

```
// Kotlin input
@TypeScript
class Foo(val bar: Boolean)

// Output
export interface Foo{}
```

Kotlin generates for `bar` the getter getBar(). A workaround is to provide a function isBar() as getter. Then the output is generated right.

```
// Kotlin input
@TypeScript
class Foo(val bar: Boolean) { isBar() = bar }

//Output
export interface Foo {
  bar: boolean
}
```

**Comment by dzuvic** [comment]
Thank you reporting this issue. This one is related to #32. At least there is workaround. I would propose fixing this issue by adding the following feature:

- add a TSModule setting for the correct Boolean prefix (is/get)
- a new TSOption annotation overriding this setting

**Comment by dzuvic** [comment]
The following changes should solve the issue, because it is now configurable. Unfortunately the name mappings aren't  quite complete. I will check, if the recent changes do solve this problem.

**Comment by dzuvic** [comment]
added a simple working Kotlin example in the jtsgen-example project. So this is finally fixed...
