### ISSUE TITLE
Hi, wil there ever bee a 0.5.0 version?

### ISSUE THREAD

**Issue by Lucas3oo** [dzuvic/jtsgen#72]
I would like to use the ENUM mapping feature.

**Comment by dzuvic** [comment]
the version 0.5.0 is on maven central.

**Comment by Lucas3oo** [comment]
great thanks!
I can't find 0.5.0 under  https://repo.maven.apache.org/maven2/com/github/dzuvic/jtsgen-processor/
but maybe it takes several days to propagate.

**Comment by Lucas3oo** [comment]
@dzuvic can you check that you actually have published version 0.5.0 since I can't find it at Maven central.

**Comment by dzuvic** [comment]
Oh, you are right. Somehow the binaries are not pushed to maven central anymore. They are only on the nexus: https://oss.sonatype.org/service/local/repositories/comgithubdzuvic-1003/content/com/github/dzuvic/jtsgen-processor/0.5.0/jtsgen-processor-0.5.0.jar

I'm analyzing it.

**Comment by dzuvic** [comment]
My bad. I forgot to press the release button. I checked if downloads from maven central sucessfully.

Thank you for reporting it..
